service: serverless-${file(serverless.vars.yml):${opt:stage, 'dev'}.product}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-3'}
  memorySize: ${file(serverless.vars.yml):${self:provider.stage}.memory, 1024}
  timeout: ${file(serverless.vars.yml):${self:provider.stage}.timeout, 60}
  environment:
    ENV_NAME: ${self:provider.stage}
functions:
  app:
    handler: app.server
